name: Publish Python Package

on:
  push:
    branches:
      - master  # 选择你要在推送时触发的分支

jobs:
  publish-python-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 使用的 Python 版本

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: |
          poetry install

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish --build
        continue-on-error: true

  build-and-release-executable:
    runs-on: ubuntu-22.04
    needs: publish-python-package
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          pip install pyinstaller

      - name: Get version
        id: get_version
        run: echo "VERSION=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Build executable
        run: |
          pyinstaller --onefile main.py --name event_trader

      - name: Rename executable
        run: |
          mv ./dist/event_trader ./dist/event_trader_v${{ steps.get_version.outputs.VERSION }}_ubuntu22.04

      - name: Create/Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          body: |
            Release for version ${{ steps.get_version.outputs.VERSION }}
            
            This release was automatically generated by the GitHub Actions workflow.
            It includes the latest executable built for Ubuntu 22.04.
          draft: false
          prerelease: false
          files: |
            ./dist/event_trader_v${{ steps.get_version.outputs.VERSION }}_ubuntu22.04
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}