name: Build and Release with Nuitka and Poetry

on:
  push:
    tags:
      - "v*.*.*"  # 只有当推送的 Tag 符合 `v*.*.*` 格式时，才会触发工作流
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu:22.04  # 选择运行环境

    steps:
      # Step 1: 检出仓库代码
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # 选择你需要的 Python 版本

      # Step 3: 安装 Poetry
      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry --version

      # Step 4: 使用 Poetry 安装项目依赖
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: 使用 Poetry 执行打包命令
      - name: Build with Nuitka
        run: |
          poetry run python -m nuitka --standalone --onefile main.py

      # Step 6: 配置 Git（设置用户名和邮箱）
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Step 7: 读取 pyproject.toml 中的版本号
      - name: Extract Version from pyproject.toml
        id: extract_version
        run: |
          pip install toml  # 安装 toml 库
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
          echo "::set-output name=version::$VERSION"  # 将版本号保存到输出变量中

      # Step 8: 创建 Release
      - name: Create Release
        if: contains(github.ref, 'tags')  # 仅在有 Tag 时执行
        uses: ncipollo/release-action@v1
        with:
          artifacts: "main.bin"  # 这是打包后的可执行文件
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub Token 发布
          tag: ${{ steps.extract_version.outputs.version }}  # 使用提取的版本号作为 Tag
          name: "Release v${{ steps.extract_version.outputs.version }}"  # 使用提取的版本号作为 Release 名称
