name: Build and Release with Nuitka and Poetry

on:
  push:
    tags:
      - "v*.*.*"  # 只有当推送的 Tag 符合 `v*.*.*` 格式时，才会触发工作流
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu:22.04  # 选择运行环境

    steps:
      # Step 1: 检出仓库代码
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # 选择你需要的 Python 版本

      # Step 3: 安装 Poetry
      - name: Install Poetry
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry --version

      # Step 4: 使用 Poetry 安装项目依赖
      - name: Install dependencies
        run: |
          poetry install

      # Step 5: 使用 Poetry 执行打包命令
      - name: Build with Nuitka
        run: |
          poetry run python -m nuitka --standalone --onefile --output-filename=event_trader.bin main.py

      # Step 6: 配置 Git（设置用户名和邮箱）
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Step 7: 读取 pyproject.toml 中的版本号
      - name: Extract Version from pyproject.toml
        id: extract_version
        run: |
          pip install toml
          VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool']['poetry']['version'])")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

        # Step 8: 创建 Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "event_trader.bin"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.extract_version.outputs.version }}
          name: "Release v${{ steps.extract_version.outputs.version }}"
        continue-on-error: true